### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by yardnsm** [yardnsm/vim-import-cost#1]
- [ ] Pretty print sizes (support also MB)
- [ ] Add syntax highlighting
- [ ] Support ranges and visually selected text
- [ ] Add an `:ImportCostSingle` to calculate the size for the current line only
- [ ] Improve speed (cache? async execution?)
